### ISSUE TITLE
Linux pip3 package installation error

### ISSUE THREAD

**Issue by ysebyy** [ossillate-inc/packj#17]
**Describe the bug**

**To Reproduce**
1. Boot up Kali VM or any other distro (tested on Ubuntu too)
2. Run `pip3 install packj`

**Expected behavior**
Packj gets installed

**Screenshots or logs**
```      [+] Checking for strace executable...OK [not found]
          [+] Clonning strace...Done
          [+] Unpacking strace (est: 2mins)...Failed [log: /tmp/strace.build.log]
      ld -shared -L. -lstrace -ldl -o libsbox.so sandbox.o
      Traceback (most recent call last):
        File "/tmp/pip-install-nrse4_2a/packj_2803a9ff09a146a3a815e8741bc39614/setup.py", line 61, in run
          setup_sandbox(target_dir)
        File "/tmp/pip-install-nrse4_2a/packj_2803a9ff09a146a3a815e8741bc39614/setup.py", line 38, in setup_sandbox
          raise Exception(f'Failed to install sandbox:\n{stderr}')
      Exception: Failed to install sandbox:
      (None, b'ld: cannot find -lstrace: No such file or directory\nld: sandbox.o: Relocations in generic ELF (EM: 62)\nld: sandbox.o: Relocations in generic ELF (EM: 62)\nld: sandbox.o: Relocations in generic ELF (EM: 62)\nld: sandbox.o: Relocations in generic ELF (EM: 62)\nld: sandbox.o: Relocations in generic ELF (EM: 62)\nld: sandbox.o: Relocations in generic ELF (EM: 62)\nld: sandbox.o: Relocations in generic ELF (EM: 62)\nld: sandbox.o: Relocations in generic ELF (EM: 62)\nld: sandbox.o: Relocations in generic ELF (EM: 62)\nld: sandbox.o: Relocations in generic ELF (EM: 62)\nld: sandbox.o: error adding symbols: file in wrong format\nmake: *** [Makefile:14: all] Error 1\n')
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-nrse4_2a/packj_2803a9ff09a146a3a815e8741bc39614/setup.py", line 65, in <module>
          setup(
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-nrse4_2a/packj_2803a9ff09a146a3a815e8741bc39614/setup.py", line 63, in run
          distutils_logger.warning(f'Custom build failed: {str(e)}! Sandbox feature will not work')
      AttributeError: module 'distutils.log' has no attribute 'warning'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> packj

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

**Desktop (please complete the following information):**
 - OS: Kali Linux (Debian) and Ubuntu, both VM

**Additional context**
Seems to fully not install, running packj afterwards throws that the package is not installed
```$ packj             
Command 'packj' not found, did you mean:
  command 'pack' from deb liballegro4-dev
  command 'packf' from deb mmh
  command 'packf' from deb nmh
  command 'pack2' from deb pack2
Try: sudo apt install <deb name>
```

**Comment by ashishbijlani** [comment]
This issue is due to lack of autoconf tool. On ubuntu try `sudo apt install autoconf build-essential` before install Packj PyPI package. Did you also try with the Docker image that we provide?
